### ISSUE TITLE
Advertisement

### ISSUE THREAD

**Issue by mmesiti** [MarieHouillon/2023-10-19-kit#1]
Tentatively: 

- [x] IBT first round
- [x] RSE@KIT first round
- [x] NHR + HPC-DIC interest lists first round
- [x] Remind people and ask them to tell us if they cannot come - first round
- [ ] Remind people and ask them to tell us if they cannot come - second round?
- [ ] IBT second round
- [ ] RSE@KIT second round
- [ ] NHR + HPC-DIC interest lists second round

**Comment by MarieHouillon** [comment]
Should we advertise on NHR + HPC-DIC interest lists now?

**Comment by mmesiti** [comment]
I guess we will have to get someone to cancel before running a second round of advertisement

**Comment by MarieHouillon** [comment]
Yes, the second round will certainly not be useful.

Le ven. 6 oct. 2023, 16:10, Michele Mesiti ***@***.***> a
écrit :
