### ISSUE TITLE
Logistics: hot beverages, biscuits, mensa booking

### ISSUE THREAD

**Issue by mmesiti** [MarieHouillon/2023-10-19-kit#2]
- [x] hot beverages:
   - [x] fiter coffee -> Michele
   - [x] tea -> Michele
- [x] biscuits -> Marie
- [x] milk -> Marie
- [x] sugar - Provided by SCC
- [x] cups - Proviced by SCC (to be washed every day with the dishwasher)
- [x] spoons -> Marie
- [x] towels -> Marie 
- [X] mensa booking: mail gastronomie@sw-ka.de or call Steffen Oertel (https://www.sw-ka.de/de/hochschulgastronomie/speiseplan/mensa_adenauerring/)

Last reply from the Mensa:
>  vielen Dank für Ihre Rückmeldung.
>  Wir werden Plätze im großen Speisesaal an der Fensterfront reservieren.
>  Weitere Informationen sind nicht notwendig, **außer die Teilnehmerzahl reduziert sich**.

**Comment by MarieHouillon** [comment]
If you want, I can take care to bring biscuits and towels.
We should also consider having some milk, sugar and spoons.

**Comment by mmesiti** [comment]
Regarding the machine to make coffee: the operation is pretty simple. 
It needs to be filled with water, filter and coffee powder and a jug must be placed in the proper place. It requires <10 minutes to brew coffee.
I can show the interested parties how to do that. In case something happens and I am not available, these are the steps:
- Locate the machine, which is between the tap and the microwave oven. It looks like the attached picture
- Fill a jug with water. There should be 2 jugs. The content of a jug is equal to a bit less than 7 mugs.
- Pour the content of the jug into the back of the machine
- Find the black bowl that can be attached to the front of the machine
- Put the filter in it
- Add coffee in the filter, a table spoon per cup. There is also a doser/measuring spoon in the cupboard above the machine for more precise measurements
- Plug the bowl with the filter and the coffee back into the machine
- Place the jug under the bowl
- Press the only button available to start the process
- Wait some minutes
- Repeat if needed

![coffee-machine](https://github.com/MarieHouillon/2023-10-19-kit/assets/8956864/0b4f2841-d670-44da-b48d-15f12e99f2d3)
